version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: tennis_scoreboard_db
    environment:
      POSTGRES_DB: "tennisdb"
      POSTGRES_USER: "tennis_user"
      POSTGRES_PASSWORD: "tennis_pass"
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro

volumes:
  postgres_data: